[package]
name = "diskpie"
description = "A fast visual disk usage scanner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[[bin]]
name = "diskpie"
path = "src/main.rs"

[dependencies]
diskpie-app = { path = "../diskpie-app", version = "0.1.0" }
diskpie-core = { path = "../diskpie-core", version = "0.1.0" }
diskpie-platform = { path = "../diskpie-platform", version = "0.1.0" }
eframe.workspace = true
lexopt.workspace = true
ron.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
winresource.workspace = true

[lints]
workspace = true
